airflow:
  fernetKey: ""
  service:
    annotations: {}
    type: ClusterIP
    externalPort: 8080
  executor: Local
  image:
    repository: cityofcapetown/airflow
    tag: kubernetes 
    pullPolicy: IfNotPresent
  webReplicas: 1 
  initdb: true 
  schedulerNumRuns: "-1"

ingress:
  enabled: true
  web:
    path: "/airflow"
    host: ""
    annotations:
      traefik.frontend.rule.type: PathPrefix
      kubernetes.io/ingress.class: traefik
    livenessPath:
    tls:
      enabled: false

rbac:
  create: true 

serviceAccount:
  create: true 
  name: airflow 

persistence:
  enabled: true
  accessMode: ReadWriteMany
  existingClaim: "airflow-dags"

logsPersistence:
  enabled: true
  accessMode: ReadWriteMany
  existingClaim: "airflow-logs"
  
postgresql:
  enabled: true
  service:
    port: 5432
  postgresUser: postgres
  postgresPassword: airflow
  postgresDatabase: airflow
  persistence:
    enabled: true
    accessMode: ReadWriteOnce

redis:
  enabled: false

workers:
  enabled: false

